name: Automation Demo

# When we push to our default branch
# runn this workflow
on:
  push:
    branches:
      - main
    workflow_dispatch:
      inputs: 
        pokemon:
          description: "Pokemon to show"
          required:
            defualt: "pikachu"

# Dfine the things to do within the workflow
jobs:

  # Run a job on Linux
  ourfirstjob:
    runs-on: ubuntu-lastest

    # Steps are the specific thing to do
    steps: 
      - run: echo "Hello, World"

      - uses: action/checkout@v4

      - run: |
          ls -a
          echo "All files of pwd listed above"

  # Run a job on Windows
  oursecondjob:
    runs-on: windows-lastest

    # Steps are the specific thing to do
    steps: 
      - name: Hello world command
        run: echo "Hello, World"
      - run: |
          ls .
          echo "All files of pwd listed above"

  pokemonimagejob:
    needs: [ourfirstjob, oursecondjob]
    name: Add Pokemon Image to Readme
    runs-on: ubuntu-latest
    steps:
      - uses: ibrahiem96/poke-readme-action@main
        with:
          pokemon: ${{ inputs.pokemon || 'pikachu' }}
        